package com.cakedelight.rating.domain;

import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * A single customer rating for one cake.
 *
 * <p>The rating service does not own cake data, so {@code cakeId} is a plain UUID column with no
 * foreign key. Identifiers are generated by this service before persisting.
 *
 * <p>Column mappings mirror {@code db/migration/V1__create_ratings.sql} exactly, because Hibernate
 * runs with {@code ddl-auto: validate} and Flyway owns the schema.
 */
@Entity
@Table(name = "ratings")
public class Rating {

    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "cake_id", nullable = false, updatable = false)
    private UUID cakeId;

    @Column(name = "customer_id", nullable = false, length = 100, updatable = false)
    private String customerId;

    /** Constrained to 1..5 by {@code CHECK (score BETWEEN 1 AND 5)} in the migration. */
    @Column(name = "score", nullable = false)
    private int score;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected Rating() {
        // required by JPA
    }

    public Rating(UUID id, UUID cakeId, String customerId, int score, Instant createdAt) {
        this.id = id;
        this.cakeId = cakeId;
        this.customerId = customerId;
        this.score = score;
        this.createdAt = createdAt;
    }

    public UUID getId() {
        return id;
    }

    public UUID getCakeId() {
        return cakeId;
    }

    public String getCustomerId() {
        return customerId;
    }

    public int getScore() {
        return score;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    @Override
    public String toString() {
        return "Rating{id=%s, cakeId=%s, customerId=%s, score=%d, createdAt=%s}"
                .formatted(id, cakeId, customerId, score, createdAt);
    }
}
