package com.cakedelight.notification.domain;

import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * One order confirmation delivery attempt: the order identifier, the delivery channel, the outcome,
 * and when it was attempted (Requirement 8.2).
 *
 * <p>The notification service does not own order data, so {@code orderId} is a plain UUID column
 * with no foreign key; orders live in {@code order_db} behind the Order Service
 * (Requirement 10.1). Identifiers are generated by this service before persisting.
 *
 * <p>A rejected attempt is stored with {@link NotificationStatus#FAILED} (Requirement 8.3), so
 * several rows can share one {@code orderId}. At most one of them can be
 * {@link NotificationStatus#SENT}, enforced by the partial unique index
 * {@code uq_notifications_order_sent} (Requirements 8.4, 8.6).
 *
 * <p>Column mappings mirror {@code db/migration/V1__create_notifications.sql} exactly, because
 * Hibernate runs with {@code ddl-auto: validate} and Flyway owns the schema. Carries no web or
 * messaging annotations.
 */
@Entity
@Table(name = "notifications")
public class Notification {

    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "order_id", nullable = false, updatable = false)
    private UUID orderId;

    /** The delivery channel used, {@code EMAIL} for this increment. */
    @Column(name = "channel", nullable = false, length = 20, updatable = false)
    private String channel;

    /** Stored as the readable enum name; the partial unique index compares it to {@code 'SENT'}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20, updatable = false)
    private NotificationStatus status;

    @Column(name = "attempted_at", nullable = false, updatable = false)
    private Instant attemptedAt;

    protected Notification() {
        // required by JPA
    }

    public Notification(
            UUID id, UUID orderId, String channel, NotificationStatus status, Instant attemptedAt) {
        this.id = id;
        this.orderId = orderId;
        this.channel = channel;
        this.status = status;
        this.attemptedAt = attemptedAt;
    }

    public UUID getId() {
        return id;
    }

    public UUID getOrderId() {
        return orderId;
    }

    public String getChannel() {
        return channel;
    }

    public NotificationStatus getStatus() {
        return status;
    }

    public Instant getAttemptedAt() {
        return attemptedAt;
    }

    @Override
    public String toString() {
        return "Notification{id=%s, orderId=%s, channel=%s, status=%s, attemptedAt=%s}"
                .formatted(id, orderId, channel, status, attemptedAt);
    }
}
