package com.cakedelight.order.domain;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Objects;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * One basket line for one customer: at most one row per {@code (customerId, cakeId)} pair, enforced
 * by {@code uq_basket_customer_cake}, which is what makes adding an already present cake a quantity
 * increment rather than a duplicate row (Requirement 3.3).
 *
 * <p>{@code cakeId} is a plain UUID with no foreign key: cake data lives in {@code catalog_db} and
 * is owned by the Catalog Service (Requirement 10.1). {@code cakeName} and {@code unitPrice} are
 * snapshots captured from the Catalog Service when the item is added (Requirement 3.2).
 *
 * <p>Persistence concern only: no web or messaging annotations, never exposed across the HTTP
 * boundary. Column mappings mirror {@code db/migration/V1__create_baskets_and_orders.sql} because
 * Hibernate runs with {@code ddl-auto: validate}.
 */
@Entity
@Table(name = "basket_items")
public class BasketItem {

    /** Identifier generated by the owning service, never by the database. */
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "customer_id", nullable = false, length = 100, updatable = false)
    private String customerId;

    @Column(name = "cake_id", nullable = false, updatable = false)
    private UUID cakeId;

    @Column(name = "cake_name", nullable = false, length = 150)
    private String cakeName;

    /** Money: {@code NUMERIC(12,2)}, always scale 2 with {@link RoundingMode#HALF_UP}. */
    @Column(name = "unit_price", nullable = false, precision = 12, scale = 2)
    private BigDecimal unitPrice;

    /** Constrained to a positive value by {@code CHECK (quantity > 0)} in the migration. */
    @Column(name = "quantity", nullable = false)
    private int quantity;

    protected BasketItem() {
        // required by JPA
    }

    public BasketItem(UUID id,
                      String customerId,
                      UUID cakeId,
                      String cakeName,
                      BigDecimal unitPrice,
                      int quantity) {
        this.id = id;
        this.customerId = customerId;
        this.cakeId = cakeId;
        this.cakeName = cakeName;
        this.unitPrice = normalize(unitPrice);
        this.quantity = quantity;
    }

    public UUID getId() {
        return id;
    }

    public String getCustomerId() {
        return customerId;
    }

    public UUID getCakeId() {
        return cakeId;
    }

    public String getCakeName() {
        return cakeName;
    }

    /** Refreshes the captured catalog name when the item is added again. */
    public void setCakeName(String cakeName) {
        this.cakeName = cakeName;
    }

    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /** Normalizes to scale 2 HALF_UP so every stored price has the same scale. */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = normalize(unitPrice);
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    /** Adds to the current quantity, used by the add-an-existing-cake path (Requirement 3.3). */
    public void increaseQuantity(int amount) {
        this.quantity += amount;
    }

    private static BigDecimal normalize(BigDecimal value) {
        return value == null ? null : value.setScale(2, RoundingMode.HALF_UP);
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof BasketItem item)) {
            return false;
        }
        return id != null && id.equals(item.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "BasketItem{id=%s, customerId=%s, cakeId=%s, unitPrice=%s, quantity=%d}"
                .formatted(id, customerId, cakeId, unitPrice, quantity);
    }
}
