package com.cakedelight.order.domain;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * A checked out order with its item snapshot (Requirements 5.1, 5.6).
 *
 * <p>{@code order} is a reserved SQL word, so the table is {@code orders} and every query goes
 * through the {@code @Table} mapping below.
 *
 * <p>Items use a JPA association rather than plain identifiers: {@code order_items.order_id} is the
 * one real foreign key in this schema (both tables are owned by this service), and
 * {@code cascade = ALL} with {@code orphanRemoval} lets the checkout transaction copy the basket
 * into the order and persist the aggregate atomically with a single save (task 5.1). The collection
 * is lazy, so callers must read it inside the transaction ({@code open-in-view} is off).
 *
 * <p>Persistence concern only: no web or messaging annotations, never exposed across the HTTP
 * boundary. Column mappings mirror {@code db/migration/V1__create_baskets_and_orders.sql} because
 * Hibernate runs with {@code ddl-auto: validate}.
 */
@Entity
@Table(name = "orders")
public class Order {

    /** Identifier generated by the owning service, never by the database. */
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "customer_id", nullable = false, length = 100, updatable = false)
    private String customerId;

    @Column(name = "customer_email", nullable = false, length = 255, updatable = false)
    private String customerEmail;

    /** Money: {@code NUMERIC(12,2)}, always scale 2 with {@link RoundingMode#HALF_UP}. */
    @Column(name = "total", nullable = false, precision = 12, scale = 2)
    private BigDecimal total;

    /** Stored as the enum name so the database value matches {@code VARCHAR(20)} readably. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private OrderStatus status;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @OneToMany(mappedBy = "order",
               cascade = CascadeType.ALL,
               orphanRemoval = true,
               fetch = FetchType.LAZY)
    // Not final: Hibernate replaces the collection instance with its own wrapper on load.
    private List<OrderItem> items = new ArrayList<>();

    protected Order() {
        // required by JPA
    }

    public Order(UUID id,
                 String customerId,
                 String customerEmail,
                 BigDecimal total,
                 OrderStatus status,
                 Instant createdAt) {
        this.id = id;
        this.customerId = customerId;
        this.customerEmail = customerEmail;
        this.total = normalize(total);
        this.status = status;
        this.createdAt = createdAt;
    }

    public UUID getId() {
        return id;
    }

    public String getCustomerId() {
        return customerId;
    }

    public String getCustomerEmail() {
        return customerEmail;
    }

    public BigDecimal getTotal() {
        return total;
    }

    /** Normalizes to scale 2 HALF_UP so every stored total has the same scale. */
    public void setTotal(BigDecimal total) {
        this.total = normalize(total);
    }

    public OrderStatus getStatus() {
        return status;
    }

    /** Only {@code CREATED -> CONFIRMED} is used; the transition itself is enforced in the service. */
    public void setStatus(OrderStatus status) {
        this.status = status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    /** Unmodifiable view; mutate through {@link #addItem(OrderItem)}. */
    public List<OrderItem> getItems() {
        return Collections.unmodifiableList(items);
    }

    /** Keeps both sides of the association in sync so the cascade inserts the child row. */
    public void addItem(OrderItem item) {
        items.add(item);
        item.setOrder(this);
    }

    private static BigDecimal normalize(BigDecimal value) {
        return value == null ? null : value.setScale(2, RoundingMode.HALF_UP);
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof Order order)) {
            return false;
        }
        return id != null && id.equals(order.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "Order{id=%s, customerId=%s, total=%s, status=%s, createdAt=%s}"
                .formatted(id, customerId, total, status, createdAt);
    }
}
