package com.cakedelight.order.domain;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Objects;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * One line of a checked out {@link Order}, copied from the basket at checkout (Requirement 5.1).
 *
 * <p>{@code cakeId} is a plain UUID with no foreign key: cake data lives in {@code catalog_db}
 * (Requirement 10.1). {@code cakeName} and {@code unitPrice} are the snapshots captured at
 * add-to-basket time, so the order reads back unchanged even if the catalog price later moves
 * (Requirement 5.6).
 *
 * <p>Persistence concern only: no web or messaging annotations, never exposed across the HTTP
 * boundary. Column mappings mirror {@code db/migration/V1__create_baskets_and_orders.sql} because
 * Hibernate runs with {@code ddl-auto: validate}.
 */
@Entity
@Table(name = "order_items")
public class OrderItem {

    /** Identifier generated by the owning service, never by the database. */
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /** Owning side of the association; {@code order_items.order_id} is a real foreign key. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "order_id", nullable = false, updatable = false)
    private Order order;

    @Column(name = "cake_id", nullable = false, updatable = false)
    private UUID cakeId;

    @Column(name = "cake_name", nullable = false, length = 150, updatable = false)
    private String cakeName;

    /** Money: {@code NUMERIC(12,2)}, always scale 2 with {@link RoundingMode#HALF_UP}. */
    @Column(name = "unit_price", nullable = false, precision = 12, scale = 2, updatable = false)
    private BigDecimal unitPrice;

    /** Constrained to a positive value by {@code CHECK (quantity > 0)} in the migration. */
    @Column(name = "quantity", nullable = false, updatable = false)
    private int quantity;

    protected OrderItem() {
        // required by JPA
    }

    public OrderItem(UUID id, UUID cakeId, String cakeName, BigDecimal unitPrice, int quantity) {
        this.id = id;
        this.cakeId = cakeId;
        this.cakeName = cakeName;
        this.unitPrice = normalize(unitPrice);
        this.quantity = quantity;
    }

    public UUID getId() {
        return id;
    }

    public Order getOrder() {
        return order;
    }

    /** Set by {@link Order#addItem(OrderItem)}; not part of the public construction contract. */
    void setOrder(Order order) {
        this.order = order;
    }

    public UUID getCakeId() {
        return cakeId;
    }

    public String getCakeName() {
        return cakeName;
    }

    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public int getQuantity() {
        return quantity;
    }

    private static BigDecimal normalize(BigDecimal value) {
        return value == null ? null : value.setScale(2, RoundingMode.HALF_UP);
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof OrderItem item)) {
            return false;
        }
        return id != null && id.equals(item.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "OrderItem{id=%s, cakeId=%s, unitPrice=%s, quantity=%d}"
                .formatted(id, cakeId, unitPrice, quantity);
    }
}
