package com.cakedelight.rating.dto;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;

/**
 * Body of {@code POST /api/cakes/{cakeId}/ratings}.
 *
 * <p>The cake identifier comes from the path, and the identifier plus the timestamp of the stored
 * rating are generated by the service, so neither appears here (Requirement 7.1).
 *
 * <p>{@code score} is boxed so that an omitted value fails {@code @NotNull} with a 400 naming the
 * field instead of silently defaulting to 0 (Requirement 7.2).
 */
public record RatingRequest(
        @NotNull(message = "customerId is required") String customerId,
        @NotNull(message = "score is required")
        @Min(value = 1, message = "score must be between 1 and 5")
        @Max(value = 5, message = "score must be between 1 and 5")
        Integer score) {
}
