package com.cakedelight.catalog.domain;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Objects;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * A cake product owned by the Catalog Service.
 *
 * <p>Persistence concern only: this entity carries no web or messaging annotations and is never
 * exposed across the HTTP boundary. Column mappings mirror {@code V1__create_cakes.sql} because
 * Hibernate runs with {@code ddl-auto: validate}.
 */
@Entity
@Table(name = "cakes")
public class Cake {

    /** Identifier generated by the owning service, never by the database. */
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "name", nullable = false, length = 150)
    private String name;

    @Column(name = "description", length = 1000)
    private String description;

    @Column(name = "category", nullable = false, length = 50)
    private String category;

    /** Money: {@code NUMERIC(12,2)}, always scale 2 with {@link RoundingMode#HALF_UP}. */
    @Column(name = "price", nullable = false, precision = 12, scale = 2)
    private BigDecimal price;

    @Column(name = "available", nullable = false)
    private boolean available;

    @Column(name = "image_url", length = 500)
    private String imageUrl;

    protected Cake() {
        // required by JPA
    }

    public Cake(UUID id,
                String name,
                String description,
                String category,
                BigDecimal price,
                boolean available,
                String imageUrl) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.category = category;
        this.price = normalize(price);
        this.available = available;
        this.imageUrl = imageUrl;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public BigDecimal getPrice() {
        return price;
    }

    /** Normalizes to scale 2 HALF_UP so every stored price has the same scale. */
    public void setPrice(BigDecimal price) {
        this.price = normalize(price);
    }

    private static BigDecimal normalize(BigDecimal value) {
        return value == null ? null : value.setScale(2, RoundingMode.HALF_UP);
    }

    public boolean isAvailable() {
        return available;
    }

    public void setAvailable(boolean available) {
        this.available = available;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof Cake cake)) {
            return false;
        }
        return id != null && id.equals(cake.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "Cake{id=" + id
                + ", name='" + name + '\''
                + ", category='" + category + '\''
                + ", price=" + price
                + ", available=" + available
                + '}';
    }
}
