-- V1__create_baskets_and_orders.sql  (H2 mirror - TEST ONLY)
--
-- Test-only mirror of src/main/resources/db/migration/V1__create_baskets_and_orders.sql, used by
-- the `test` Spring profile (src/test/resources/application-test.yml). db/migration/ remains the
-- source of truth for PostgreSQL 16; nothing here ships in the application jar.
--
-- CHANGED FOR H2:
--   * `orders.created_at` is spelled `TIMESTAMP WITH TIME ZONE` instead of the PostgreSQL-only
--     alias `TIMESTAMPTZ`. H2 does not recognise `TIMESTAMPTZ` as a type name, even in
--     MODE=PostgreSQL. Same SQL type, same semantics, same JDBC mapping.
--
-- Nothing else diverges. Table names, column names, column order, types, nullability, CHECK
-- constraints, the composite UNIQUE constraint and the ON DELETE CASCADE foreign key are all
-- supported by H2 and reproduced verbatim, so `ddl-auto: validate` still catches entity drift.
--
-- Owns baskets and orders only. cake_id in basket_items and order_items is a plain UUID column:
-- cake data lives in catalog_db and is owned by the Catalog Service, so no foreign key is
-- possible here (Requirement 10.1). cake_name and unit_price are snapshots captured from the
-- Catalog Service at add-to-basket time (Requirement 3.2). Money is NUMERIC(12,2), never a
-- floating point type; identifiers are UUIDs generated by this service.

-- uq_basket_customer_cake is what makes "add an existing cake" a quantity increment rather than
-- a duplicate row (Requirement 3.3).
CREATE TABLE basket_items (
    id          UUID PRIMARY KEY,
    customer_id VARCHAR(100)  NOT NULL,
    cake_id     UUID          NOT NULL,
    cake_name   VARCHAR(150)  NOT NULL,
    unit_price  NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    quantity    INTEGER       NOT NULL CHECK (quantity > 0),
    CONSTRAINT uq_basket_customer_cake UNIQUE (customer_id, cake_id)
);

-- Backs the basket view (Requirement 4.1) and the checkout clear (Requirement 5.3).
CREATE INDEX idx_basket_items_customer ON basket_items (customer_id);

-- status holds the OrderStatus enum name (CREATED, CONFIRMED); total equals the basket total
-- captured at checkout (Requirement 5.1).
CREATE TABLE orders (
    id             UUID PRIMARY KEY,
    customer_id    VARCHAR(100)             NOT NULL,
    customer_email VARCHAR(255)             NOT NULL,
    total          NUMERIC(12,2)            NOT NULL CHECK (total >= 0),
    status         VARCHAR(20)              NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_orders_customer ON orders (customer_id);

-- order_items mirror the basket items at checkout (Requirements 5.1, 5.3). order_id is the one
-- foreign key in this schema, since orders is owned by this same service.
CREATE TABLE order_items (
    id         UUID PRIMARY KEY,
    order_id   UUID          NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    cake_id    UUID          NOT NULL,
    cake_name  VARCHAR(150)  NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    quantity   INTEGER       NOT NULL CHECK (quantity > 0)
);

CREATE INDEX idx_order_items_order ON order_items (order_id);
